//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsnet
{
    using System;
    using System.Collections.Generic;

     [Serializable]
    public partial class ProductType
    {
        public ProductType()
        {
            this.tbl_Products = new HashSet<Products>();
        }
    
        public int ProductTypeId { get; set; }
        public string Title { get; set; }
        public int Period { get; set; }
    
        public virtual ICollection<Products> tbl_Products { get; set; }
    }
}
