//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsnet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Logins> tbl_Logins { get; set; }
        public DbSet<Payments> tbl_Payments { get; set; }
        public DbSet<Products> tbl_Products { get; set; }
        public DbSet<ProductType> tbl_ProductType { get; set; }
        public DbSet<Requests> tbl_Requests { get; set; }
        public DbSet<RequestType> tbl_RequestType { get; set; }
        public DbSet<Scores> tbl_Scores { get; set; }
        public DbSet<ScoreType> tbl_ScoreType { get; set; }
        public DbSet<Sites> tbl_Sites { get; set; }
        public DbSet<Users> tbl_Users { get; set; }
        public DbSet<UserState> tbl_UserState { get; set; }
        public DbSet<Visits> tbl_Visits { get; set; }
    }
}
