//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsnet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentId { get; set; }
        public int UserId { get; set; }
        public int ProductId { get; set; }
        public int IdGet { get; set; }
        public Nullable<int> TransId { get; set; }
        public int Status { get; set; }
        public System.DateTime PayDate { get; set; }
        public int Amount { get; set; }
    
        public virtual Products tbl_Products { get; set; }
        public virtual Users tbl_Users { get; set; }
    }
}
