//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsnet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int RequestId { get; set; }
        public int RequestTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string IP { get; set; }
        public string SystemId { get; set; }
    
        public virtual RequestType tbl_RequestType { get; set; }
        public virtual Users tbl_Users { get; set; }
    }
}
