//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsnet
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestType
    {
        public RequestType()
        {
            this.tbl_Requests = new HashSet<Requests>();
        }
    
        public int RequestTypeId { get; set; }
        public string CommandName { get; set; }
    
        public virtual ICollection<Requests> tbl_Requests { get; set; }
    }
}
