//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsnet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int ScoreId { get; set; }
        public int ScoreTypeId { get; set; }
        public int UserId { get; set; }
        public int Value { get; set; }
        public System.DateTime GetDate { get; set; }
    
        public virtual ScoreType tbl_ScoreType { get; set; }
        public virtual Users tbl_Users { get; set; }
    }
}
