//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsnet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreType
    {
        public ScoreType()
        {
            this.tbl_Scores = new HashSet<Scores>();
        }
    
        public int ScoreTypeId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Scores> tbl_Scores { get; set; }
    }
}
