//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsnet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.tbl_Logins = new HashSet<Logins>();
            this.tbl_Payments = new HashSet<Payments>();
            this.tbl_Requests = new HashSet<Requests>();
            this.tbl_Scores = new HashSet<Scores>();
            this.tbl_Sites = new HashSet<Sites>();
            this.tbl_Visits = new HashSet<Visits>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int StateId { get; set; }
        public int ScoreStep { get; set; }
        public string ConfirmCode { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        public virtual ICollection<Logins> tbl_Logins { get; set; }
        public virtual ICollection<Payments> tbl_Payments { get; set; }
        public virtual ICollection<Requests> tbl_Requests { get; set; }
        public virtual ICollection<Scores> tbl_Scores { get; set; }
        public virtual ICollection<Sites> tbl_Sites { get; set; }
        public virtual UserState tbl_UserState { get; set; }
        public virtual ICollection<Visits> tbl_Visits { get; set; }
    }
}
