//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsnet
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserState
    {
        public UserState()
        {
            this.tbl_Users = new HashSet<Users>();
        }
    
        public int StateId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Users> tbl_Users { get; set; }
    }
}
