//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsnet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int VisitId { get; set; }
        public string IP { get; set; }
        public int SiteId { get; set; }
        public int UserId { get; set; }
        public System.DateTime VisitDate { get; set; }
    
        public virtual Sites tbl_Sites { get; set; }
        public virtual Users tbl_Users { get; set; }
    }
}
