//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.19462
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parsnet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Revision {
            get {
                return ((decimal)(this["Revision"]));
            }
            set {
                this["Revision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Build {
            get {
                return ((decimal)(this["Build"]));
            }
            set {
                this["Build"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.rizeh.com/Client/RizehClient.exe")]
        public string ClientFilePath {
            get {
                return ((string)(this["ClientFilePath"]));
            }
            set {
                this["ClientFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal Major {
            get {
                return ((decimal)(this["Major"]));
            }
            set {
                this["Major"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Minor {
            get {
                return ((decimal)(this["Minor"]));
            }
            set {
                this["Minor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<!DOCTYPE html>\r\n\r\n<html lang=\""en\"" xmlns=\""http://www.w3.org/1999/xhtml\"">\r\n<head>\r\n    <meta charset=\""utf-8\"" />\r\n    <title></title>\r\n</head>\r\n<body>\r\n    <div style=\""direction: rtl; text-align: justify; font-family: Tahoma; font-size: 14px; line-height: 18px;\"">\r\n        برای بازنشانی رمز عبور خود در نرم افزار ریزه بر روی لینک زیر کلیک کنید:<br />\r\n    <a href=\""[Url]\"">بازنشانی رمز عبور در ریزه</a>\r\n    </div>\r\n</body>\r\n</html>")]
        public string ResetPasswordEmail {
            get {
                return ((string)(this["ResetPasswordEmail"]));
            }
            set {
                this["ResetPasswordEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal ScoreStep {
            get {
                return ((decimal)(this["ScoreStep"]));
            }
            set {
                this["ScoreStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7070")]
        public int ServerPort {
            get {
                return ((int)(this["ServerPort"]));
            }
            set {
                this["ServerPort"] = value;
            }
        }
    }
}
